export interface WikiModel {
  id: string;
  slug: string;
  name: string;
  thinker: string;
  color: string;
  icon: string;
  definition: string;
  detailedContent: string[];
  triggerQuestion: string;
  example: string;
}

export const wikiContent: WikiModel[] = [
  {
    "id": "incentivos--super-resposta",
    "slug": "incentivos--super-resposta",
    "name": "Incentivos (Super-resposta)",
    "thinker": "Estratégia Coletiva",
    "color": "#FF6B6B",
    "icon": "↻",
    "definition": "Pessoas agem por recompensas e evitam punições (não se importam com suas boas intenções).",
    "detailedContent": [],
    "triggerQuestion": "Antes de pedir algo a um cliente ou sócio, mostre primeiro e de forma clara o que ele ganha com isso.",
    "example": "Agências sugerem campanhas caras apenas porque ganham comissão sobre o orçamento investido."
  },
  {
    "id": "prova-social",
    "slug": "prova-social",
    "name": "Prova Social",
    "thinker": "Robert Cialdini",
    "color": "#4ECDC4",
    "icon": "◇",
    "definition": "O instinto de seguir a manada quando se está na dúvida.",
    "detailedContent": [],
    "triggerQuestion": "Adicione um bloco de avaliações (Quem já usou) na sua oferta principal hoje.",
    "example": "Colocar depoimentos em vídeo na landing page do seu curso de IA converte mais que prometer mundos e fundos sozinho."
  },
  {
    "id": "reciprocidade",
    "slug": "reciprocidade",
    "name": "Reciprocidade",
    "thinker": "Robert Cialdini",
    "color": "#F59E0B",
    "icon": "⊖",
    "definition": "A urgência psicológica em retribuir favores recebidos.",
    "detailedContent": [],
    "triggerQuestion": "Resolva um problema pequeno de um prospect no WhatsApp de graça, sem pedir nada em troca.",
    "example": "Entregar um diagnóstico gratuito e valioso de Holding Familiar antes de tentar vender a consultoria."
  },
  {
    "id": "aversao-a-perda",
    "slug": "aversao-a-perda",
    "name": "Aversão à Perda",
    "thinker": "Daniel Kahneman",
    "color": "#FFE66D",
    "icon": "◌",
    "definition": "A dor de perder dinheiro dói o dobro do prazer de ganhá-lo.",
    "detailedContent": [],
    "triggerQuestion": "Reformule uma headline focando estritamente no que o cliente perde se não te contratar.",
    "example": "O anúncio \"Veja o dinheiro que sua empresa queima ao ignorar a IA\" tem taxa de clique maior que \"Ganhe mais dinheiro com IA\"."
  },
  {
    "id": "vies-de-autoridade",
    "slug": "vies-de-autoridade",
    "name": "Viés de Autoridade",
    "thinker": "Estratégia Coletiva",
    "color": "#A78BFA",
    "icon": "⟁",
    "definition": "A tendência humana de não questionar quem parece especialista.",
    "detailedContent": [],
    "triggerQuestion": "Remova o jargão técnico da sua próxima reunião e avalie se o cliente entende o valor real do seu serviço.",
    "example": "O cliente aceita taxas ruins porque o gerente do banco está de terno e em uma sala de vidro."
  },
  {
    "id": "efeito-lollapalooza",
    "slug": "efeito-lollapalooza",
    "name": "Efeito Lollapalooza",
    "thinker": "Charlie Munger",
    "color": "#F97316",
    "icon": "◎",
    "definition": "Múltiplos vieses empurrando na mesma direção para gerar uma decisão extrema.",
    "detailedContent": [],
    "triggerQuestion": "Combine escassez (bônus some hoje) com prova social (x pessoas já compraram) na abertura do carrinho.",
    "example": "Um leilão mistura escassez, urgência e prova social, forçando lances irracionais."
  },
  {
    "id": "vies-de-confirmacao",
    "slug": "vies-de-confirmacao",
    "name": "Viés de Confirmação",
    "thinker": "Estratégia Coletiva",
    "color": "#38BDF8",
    "icon": "⟋",
    "definition": "Buscar apenas informações que confirmem aquilo que você já decidiu acreditar.",
    "detailedContent": [],
    "triggerQuestion": "Liste agora 3 motivos sólidos pelos quais seu principal projeto atual pode fracassar.",
    "example": "O trader que só lê fóruns otimistas sobre a moeda que comprou e ignora os sinais gráficos de queda."
  },
  {
    "id": "vies-de-disponibilidade",
    "slug": "vies-de-disponibilidade",
    "name": "Viés de Disponibilidade",
    "thinker": "Estratégia Coletiva",
    "color": "#E879F9",
    "icon": "⊘",
    "definition": "Acreditar que algo é frequente ou provável só porque é fácil de lembrar.",
    "detailedContent": [],
    "triggerQuestion": "Busque os números reais do mercado (taxa média de conversão do nicho) em vez de focar nos prints de gurus.",
    "example": "Achar que todo negócio digital fatura milhões rápido porque seu feed do Instagram só mostra os vencedores."
  },
  {
    "id": "inveja--envy",
    "slug": "inveja--envy",
    "name": "Inveja (Envy)",
    "thinker": "Charlie Munger",
    "color": "#94A3B8",
    "icon": "◈",
    "definition": "Para Munger, a inveja, não a ganância, é o motor oculto do mundo.",
    "detailedContent": [],
    "triggerQuestion": "Identifique a última compra cara que você fez apenas para impressionar outras pessoas.",
    "example": "Pessoas trocam de carro para sinalizar status aos vizinhos, não por eficiência."
  },
  {
    "id": "evitacao-de-inconsistencia",
    "slug": "evitacao-de-inconsistencia",
    "name": "Evitação de Inconsistência",
    "thinker": "Estratégia Coletiva",
    "color": "#34D399",
    "icon": "⊛",
    "definition": "A dificuldade extrema em mudar de ideia após assumir uma postura pública.",
    "detailedContent": [],
    "triggerQuestion": "Admita publicamente um erro ou tese errada sua para a equipe nesta semana.",
    "example": "O empresário que continua queimando caixa num produto ruim porque foi ele quem teve a ideia."
  },
  {
    "id": "inversao",
    "slug": "inversao",
    "name": "Inversão",
    "thinker": "Charlie Munger",
    "color": "#FF6B6B",
    "icon": "⊙",
    "definition": "Pensar em como fracassar (para evitar) em vez de pensar em como ter sucesso.",
    "detailedContent": [],
    "triggerQuestion": "Liste 5 atitudes que quebrariam seu negócio digital em 6 meses, e crie barreiras contra elas.",
    "example": "Para ficar rico, o passo 1 é listar e fugir de apostas estúpidas que levam à ruína."
  },
  {
    "id": "pensamento-de-segunda-ordem",
    "slug": "pensamento-de-segunda-ordem",
    "name": "Pensamento de Segunda Ordem",
    "thinker": "Howard Marks",
    "color": "#4ECDC4",
    "icon": "⊕",
    "definition": "Perguntar sempre (E depois disso, o que acontece?).",
    "detailedContent": [],
    "triggerQuestion": "Antes da sua próxima decisão grande, anote as consequências esperadas daqui a 1 semana e daqui a 1 ano.",
    "example": "Demitir o suporte gera economia hoje (1ª ordem), mas mancha sua marca no ReclameAqui amanhã (2ª ordem)."
  },
  {
    "id": "custo-de-oportunidade",
    "slug": "custo-de-oportunidade",
    "name": "Custo de Oportunidade",
    "thinker": "Economia Clássica",
    "color": "#F59E0B",
    "icon": "⊟",
    "definition": "O valor real de uma escolha é aquilo que você precisou sacrificar para fazê-la.",
    "detailedContent": [],
    "triggerQuestion": "Defina o preço financeiro da sua hora e delegue qualquer tarefa operacional que custe menos que isso.",
    "example": "Passar 4 horas formatando um PDF custa as 4 horas que você poderia gastar fechando contratos High Ticket."
  },
  {
    "id": "margem-de-seguranca",
    "slug": "margem-de-seguranca",
    "name": "Margem de Segurança",
    "thinker": "Benjamin Graham",
    "color": "#FFE66D",
    "icon": "⊞",
    "definition": "Deixar espaço para o erro sistêmico.",
    "detailedContent": [],
    "triggerQuestion": "Quando um cliente perguntar o prazo de entrega, calcule o ideal e adicione 20% de \"gordura\".",
    "example": "Só colocar em testes de campanhas novas do Meta um orçamento que, se perdido 100%, não afeta sua vida pessoal."
  },
  {
    "id": "circulo-de-competencia",
    "slug": "circulo-de-competencia",
    "name": "Círculo de Competência",
    "thinker": "Warren Buffett",
    "color": "#A78BFA",
    "icon": "☽",
    "definition": "Operar apenas dentro do perímetro do que você entende profundamente.",
    "detailedContent": [],
    "triggerQuestion": "Escreva no bloco de notas 3 áreas que você domina e 3 áreas que você precisa ignorar porque não entende.",
    "example": "Focar em marketing direto, automações de IA e consultorias, evitando investir na nova criptomoeda exótica do dia."
  },
  {
    "id": "navalha-de-occam",
    "slug": "navalha-de-occam",
    "name": "Navalha de Occam",
    "thinker": "William de Ockham",
    "color": "#F97316",
    "icon": "⚑",
    "definition": "Entre duas explicações para o mesmo problema, a mais simples costuma ser a correta.",
    "detailedContent": [],
    "triggerQuestion": "Corte um passo desnecessário do seu funil de vendas ativo.",
    "example": "Se o lead do WhatsApp sumiu, ele não foi bloqueado pela operadora, a oferta apenas não foi boa o suficiente."
  },
  {
    "id": "navalha-de-hanlon",
    "slug": "navalha-de-hanlon",
    "name": "Navalha de Hanlon",
    "thinker": "Robert J. Hanlon",
    "color": "#38BDF8",
    "icon": "✧",
    "definition": "Nunca atribua à malícia o que pode ser explicado pela incompetência.",
    "detailedContent": [],
    "triggerQuestion": "Na próxima falha do fornecedor, assuma confusão e exija um processo melhor, não fique ofendido.",
    "example": "Seu parceiro não te copiou no e-mail para te sabotar, ele apenas estava desatento."
  },
  {
    "id": "o-mapa-nao-e-o-territorio",
    "slug": "o-mapa-nao-e-o-territorio",
    "name": "O Mapa Não é o Território",
    "thinker": "Alfred Korzybski",
    "color": "#E879F9",
    "icon": "Δ",
    "definition": "Planilhas e planos teóricos não sobrevivem perfeitamente ao contato com a realidade.",
    "detailedContent": [],
    "triggerQuestion": "Coloque o MVP rodando no mercado com verba mínima em vez de passar o mês refinando o planejamento.",
    "example": "O ROAS projetado de 10x na planilha despenca quando os clientes reais não entendem o criativo do anúncio."
  },
  {
    "id": "a-sindrome-do-homem-com-o-martelo",
    "slug": "a-sindrome-do-homem-com-o-martelo",
    "name": "A Síndrome do Homem com o Martelo",
    "thinker": "Estratégia Coletiva",
    "color": "#94A3B8",
    "icon": "∇",
    "definition": "Para quem só tem um martelo, qualquer problema parece prego.",
    "detailedContent": [],
    "triggerQuestion": "Quando empacar em um gargalo, peça opinião a alguém de um mercado completamente diferente do seu.",
    "example": "Um programador acha que falta de vendas se resolve refazendo código, enquanto o problema é a falta de tráfego."
  },
  {
    "id": "pensamento-por-primeiros-principios",
    "slug": "pensamento-por-primeiros-principios",
    "name": "Pensamento por Primeiros Princípios",
    "thinker": "Aristóteles / Elon Musk",
    "color": "#34D399",
    "icon": "⋈",
    "definition": "Desconstruir um problema até seus blocos fundamentais de verdade indiscutível.",
    "detailedContent": [],
    "triggerQuestion": "Pegue um (fato) aceito do seu mercado (Ex: preciso postar todo dia) e pergunte o porquê até chegar na base.",
    "example": "Em vez de cobrar igual ao concorrente pelo curso, calcule o custo do servidor, tráfego, seu tempo e construa o preço da base para cima."
  },
  {
    "id": "vantagem-competitiva--moat",
    "slug": "vantagem-competitiva--moat",
    "name": "Vantagem Competitiva (Moat)",
    "thinker": "Warren Buffett",
    "color": "#FF6B6B",
    "icon": "↻",
    "definition": "O fosso intransponível que protege seu lucro dos competidores.",
    "detailedContent": [],
    "triggerQuestion": "Liste um diferencial do seu serviço que seja absurdamente caro ou doloroso para um rival tentar copiar.",
    "example": "A burocracia complexa que você resolve para as famílias ricas cria uma barreira gigante para amadores tentarem roubar o cliente."
  },
  {
    "id": "economia-de-escala",
    "slug": "economia-de-escala",
    "name": "Economia de Escala",
    "thinker": "Estratégia Coletiva",
    "color": "#4ECDC4",
    "icon": "◇",
    "definition": "O custo por unidade despenca à medida que o volume aumenta.",
    "detailedContent": [],
    "triggerQuestion": "Aloque 20% do seu tempo de hoje criando um ativo de informação que possa ser vendido infinitas vezes.",
    "example": "Gravar as aulas e hospedar uma plataforma de IA tem o mesmo custo fixo para 10 ou 1.000 alunos."
  },
  {
    "id": "efeitos-de-rede",
    "slug": "efeitos-de-rede",
    "name": "Efeitos de Rede",
    "thinker": "Estratégia Coletiva",
    "color": "#F59E0B",
    "icon": "⊖",
    "definition": "O produto ganha mais valor para o usuário a cada novo usuário que entra.",
    "detailedContent": [],
    "triggerQuestion": "Crie um ambiente onde seus clientes interajam entre si e gerem dados ou negócios uns para os outros.",
    "example": "Um grupo ou comunidade de alunos onde o networking entre eles vira o produto principal."
  },
  {
    "id": "custos-de-troca--switching-costs",
    "slug": "custos-de-troca--switching-costs",
    "name": "Custos de Troca (Switching Costs)",
    "thinker": "Estratégia Coletiva",
    "color": "#FFE66D",
    "icon": "◌",
    "definition": "A dor de cabeça de mudar de fornecedor.",
    "detailedContent": [],
    "triggerQuestion": "Faça seu serviço ou consultoria se conectar intimamente à rotina operacional diária do cliente.",
    "example": "Empresas não trocam sistemas de CRM ruins porque o custo de treinar 50 funcionários de novo é altíssimo."
  },
  {
    "id": "alavancagem",
    "slug": "alavancagem",
    "name": "Alavancagem",
    "thinker": "Estratégia Coletiva",
    "color": "#A78BFA",
    "icon": "⟁",
    "definition": "Usar Código, Capital, Mídia ou Mão de obra para multiplicar seus resultados com o mesmo esforço de base.",
    "detailedContent": [],
    "triggerQuestion": "Identifique uma tarefa que consome 1h por dia e automatize-a hoje mesmo usando IA.",
    "example": "Um vídeo curto ou automação de disparo operando 24 horas por dia por você é alavancagem de mídia/código."
  },
  {
    "id": "destruicao-criativa",
    "slug": "destruicao-criativa",
    "name": "Destruição Criativa",
    "thinker": "Joseph Schumpeter",
    "color": "#F97316",
    "icon": "◎",
    "definition": "Inovações de base eliminam mercados velhos para criar novos.",
    "detailedContent": [],
    "triggerQuestion": "Defina hoje qual frente do seu modelo de negócios vai desaparecer com a IA, e seja o primeiro a fazer a transição.",
    "example": "Agências de tráfego braçal perdendo espaço para sistemas de otimização nativos e IAs focadas em criativos."
  },
  {
    "id": "gargalo--teoria-das-restricoes",
    "slug": "gargalo--teoria-das-restricoes",
    "name": "Gargalo (Teoria das Restrições)",
    "thinker": "Estratégia Coletiva",
    "color": "#38BDF8",
    "icon": "⟋",
    "definition": "O processo mais lento dita a velocidade máxima da empresa inteira.",
    "detailedContent": [],
    "triggerQuestion": "Encontre a etapa exata onde seus clientes abandonam o funil e melhore exclusivamente ela antes de escalar.",
    "example": "Injetar 5 mil reais no tráfego não serve de nada se você tem apenas uma pessoa fechando vendas no WhatsApp."
  },
  {
    "id": "selecao-adversa",
    "slug": "selecao-adversa",
    "name": "Seleção Adversa",
    "thinker": "Estratégia Coletiva",
    "color": "#E879F9",
    "icon": "⊘",
    "definition": "Assimetrias de regras atraem o tipo exato de pessoa que você não quer.",
    "detailedContent": [],
    "triggerQuestion": "Crie um filtro (como um formulário ou aumento de preço inicial) para remover clientes sugadores da sua agenda.",
    "example": "Oferecer 30 dias de teste gratuito num serviço de luxo só atrai curiosos sem dinheiro e entope o suporte."
  },
  {
    "id": "oferta-e-demanda",
    "slug": "oferta-e-demanda",
    "name": "Oferta e Demanda",
    "thinker": "Estratégia Coletiva",
    "color": "#94A3B8",
    "icon": "◈",
    "definition": "O preço sobe na escassez e desaba na abundância.",
    "detailedContent": [],
    "triggerQuestion": "Crie escassez verídica de tempo ou assentos para o seu próximo produto e aumente o preço.",
    "example": "CPM de anúncios subindo estratosfericamente nas semanas de Black Friday devido à alta procura de empresas por atenção."
  },
  {
    "id": "agente-principal--problema-de-agencia",
    "slug": "agente-principal--problema-de-agencia",
    "name": "Agente-Principal (Problema de Agência)",
    "thinker": "Estratégia Coletiva",
    "color": "#34D399",
    "icon": "⊛",
    "definition": "Quem gerencia as operações tem incentivos conflitantes com os interesses de quem é o dono do dinheiro.",
    "detailedContent": [],
    "triggerQuestion": "Alinhe financeiramente a sua equipe (ou você com os clientes de holding) atrelando bônus diretamente aos resultados finais.",
    "example": "O gestor terceirizado torra a verba para mostrar (alcance), enquanto você, o dono, só quer (lucro)."
  },
  {
    "id": "juros-compostos--compounding",
    "slug": "juros-compostos--compounding",
    "name": "Juros Compostos (Compounding)",
    "thinker": "Albert Einstein / Naval",
    "color": "#FF6B6B",
    "icon": "⊙",
    "definition": "Crescimento exponencial contínuo; funciona para dinheiro, hábitos e conhecimento.",
    "detailedContent": [],
    "triggerQuestion": "Escolha um único hábito intelectual focado de 20 minutos diários e não quebre a rotina nesta semana.",
    "example": "Aprender um pouco de prompt engineering todo dia te dá capacidade de montar produtos complexos em 6 meses que novatos não alcançam."
  },
  {
    "id": "valor-esperado--ev",
    "slug": "valor-esperado--ev",
    "name": "Valor Esperado (EV)",
    "thinker": "Blaise Pascal / Von Neumann",
    "color": "#4ECDC4",
    "icon": "⊕",
    "definition": "O balanço matemático entre a probabilidade de acerto (vezes o prêmio) e a probabilidade de erro (vezes o custo).",
    "detailedContent": [],
    "triggerQuestion": "Antes de comprar tráfego amanhã, verifique mentalmente se a pior hipótese custa pouco e a melhor hipótese paga todo o risco.",
    "example": "Investir R$ 200 para testar um funil com 10% de chance de ganhar um contrato anual de R$ 10.000 é um EV extremamente alto."
  },
  {
    "id": "assimetria-de-risco",
    "slug": "assimetria-de-risco",
    "name": "Assimetria de Risco",
    "thinker": "Nassim Taleb",
    "color": "#F59E0B",
    "icon": "⊟",
    "definition": "Estruturas onde você perde muito pouco se der errado, mas o teto de ganhos é incalculável.",
    "detailedContent": [],
    "triggerQuestion": "Mate hoje qualquer projeto na sua gaveta que consuma seu tempo de forma fixa (alto custo) com teto baixo de faturamento.",
    "example": "Lançar um infoproduto gravado. Seu custo foi apenas o tempo de fim de semana, mas pode escalar infinitamente."
  },
  {
    "id": "regressao-a-media",
    "slug": "regressao-a-media",
    "name": "Regressão à Média",
    "thinker": "Estratégia Coletiva",
    "color": "#FFE66D",
    "icon": "⊞",
    "definition": "Após resultados atípicos ou extremos, o sistema tende a voltar para a média histórica.",
    "detailedContent": [],
    "triggerQuestion": "Não mude completamente sua estratégia comercial baseando-se em apenas um pico isolado (para cima ou para baixo).",
    "example": "O ROAS estúpido de 15x de segunda-feira fatalmente vai cair para 3x até o domingo."
  },
  {
    "id": "lei-dos-grandes-numeros",
    "slug": "lei-dos-grandes-numeros",
    "name": "Lei dos Grandes Números",
    "thinker": "Estratégia Coletiva",
    "color": "#A78BFA",
    "icon": "☽",
    "definition": "Padrões sólidos exigem amostragem volumosa, pois testes pequenos engolem flutuações.",
    "detailedContent": [],
    "triggerQuestion": "Espere pelo menos bater um número estatisticamente relevante (Ex: 100 leads) antes de decretar o fim de uma estratégia.",
    "example": "Desligar um anúncio porque os 5 primeiros cliques não compraram, jogando fora o potencial de otimização de campanha."
  },
  {
    "id": "caudas-gordas--cisnes-negros",
    "slug": "caudas-gordas--cisnes-negros",
    "name": "Caudas Gordas (Cisnes Negros)",
    "thinker": "Nassim Taleb",
    "color": "#F97316",
    "icon": "⚑",
    "definition": "A vida real não é uma curva normal perfeita; eventos imprevisíveis causam a maior parte da destruição ou da riqueza.",
    "detailedContent": [],
    "triggerQuestion": "Olhe para o seu caixa hoje. Ele sobrevive a 3 meses de interrupção forçada se sua principal fonte de aquisição quebrar?",
    "example": "Mudanças súbitas e devastadoras no algoritmo de entrega do Instagram que apagam negócios da noite para o dia."
  },
  {
    "id": "redundancia--backups",
    "slug": "redundancia--backups",
    "name": "Redundância (Backups)",
    "thinker": "Estratégia Coletiva",
    "color": "#38BDF8",
    "icon": "✧",
    "definition": "Camadas de segurança parciais para que a falha de uma peça não derrube o sistema inteiro.",
    "detailedContent": [],
    "triggerQuestion": "Faça backup offline do contato dos seus clientes principais e dos dados financeiros mais críticos da holding.",
    "example": "Estruturas de contingência com múltiplos BMs, perfis e contas de anúncios caso o Meta bloqueie um administrador."
  },
  {
    "id": "massa-critica--tipping-point",
    "slug": "massa-critica--tipping-point",
    "name": "Massa Crítica (Tipping Point)",
    "thinker": "Estratégia Coletiva",
    "color": "#E879F9",
    "icon": "Δ",
    "definition": "O limite exato de energia injetada onde a mudança ganha ritmo automático.",
    "detailedContent": [],
    "triggerQuestion": "Insista brutalmente no operacional não escalável (como vendas via 1 a 1) até juntar avaliações suficientes para a máquina rodar sozinha.",
    "example": "Um infoproduto não traciona até conseguir dezenas de depoimentos base; depois que a prova social se forma, ele se vende sozinho."
  },
  {
    "id": "sistemas-complexos--nao-linearidade",
    "slug": "sistemas-complexos--nao-linearidade",
    "name": "Sistemas Complexos (Não-linearidade)",
    "thinker": "Estratégia Coletiva",
    "color": "#94A3B8",
    "icon": "∇",
    "definition": "Mais força aplicada nem sempre gera resultados proporcionais na ponta.",
    "detailedContent": [],
    "triggerQuestion": "Pare de socar recursos em um processo desgastado. Gaste o tempo pivotando a oferta criativa.",
    "example": "Injetar o triplo de dinheiro no mesmo criativo e no mesmo público não te dará o triplo de vendas (satura a frequência)."
  },
  {
    "id": "ciclos-de-feedback--loops",
    "slug": "ciclos-de-feedback--loops",
    "name": "Ciclos de Feedback (Loops)",
    "thinker": "Estratégia Coletiva",
    "color": "#34D399",
    "icon": "⋈",
    "definition": "Processos onde a saída anterior é utilizada como a entrada seguinte do sistema.",
    "detailedContent": [],
    "triggerQuestion": "Bloqueie na agenda de sexta-feira 15 minutos focados exclusivamente em revisão de métricas para definir o loop tático da semana seguinte.",
    "example": "O Pixel de inteligência aprendendo quem compra (Feedback Positivo) para buscar leads idênticos cada vez mais qualificados."
  }
];
